/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_8 (
    input [3:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] cmp_out
  );
  
  
  
  reg cmp;
  
  always @* begin
    
    case (alufn[1+1-:2])
      1'h1: begin
        cmp = z;
      end
      4'ha: begin
        cmp = n ^ v;
      end
      4'hb: begin
        cmp = z | (n ^ v);
      end
      default: begin
        cmp = 1'h0;
      end
    endcase
    cmp_out[0+0-:1] = cmp;
    cmp_out[1+14-:15] = 15'h0000;
  end
endmodule
