/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_9 (
    input [3:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum_out,
    output reg z_,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = $signed(a) + $signed(b);
      end
      2'h1: begin
        sum = $signed(a) - $signed(b);
      end
      2'h2: begin
        sum = $signed(a) * $signed(b);
      end
      2'h3: begin
        sum = a / b;
      end
      default: begin
        sum = 14'h270f;
      end
    endcase
    sum_out = sum[0+15-:16];
    if (sum == 2'h0) begin
      z_ = 1'h1;
    end else begin
      z_ = 1'h0;
    end
    v = (~a[15+0-:1] & b[15+0-:1] & (sum[15+0-:1])) | ((a[15+0-:1]) & (~b[15+0-:1]) & ~(sum[15+0-:1]));
    n = sum[15+0-:1];
  end
endmodule
