/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testcase_8 (
    input clk,
    input rst,
    input button_alu,
    output reg [15:0] display
  );
  
  
  
  wire [16-1:0] M_alu_alu;
  wire [3-1:0] M_alu_zvn;
  reg [6-1:0] M_alu_alufn;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  alu_1 alu (
    .alufn(M_alu_alufn),
    .a(M_alu_a),
    .b(M_alu_b),
    .alu(M_alu_alu),
    .zvn(M_alu_zvn)
  );
  
  localparam START_state = 5'd0;
  localparam ADDPOS_state = 5'd1;
  localparam ADDNEG_state = 5'd2;
  localparam OVERFLOW_state = 5'd3;
  localparam SUBPOS_state = 5'd4;
  localparam SUBNEG_state = 5'd5;
  localparam UNDERFLOW_state = 5'd6;
  localparam MULT_state = 5'd7;
  localparam DIV_state = 5'd8;
  localparam CMPLEV_state = 5'd9;
  localparam CMPLEI_state = 5'd10;
  localparam CMPLTV_state = 5'd11;
  localparam CMPLTI_state = 5'd12;
  localparam CMPEQ_state = 5'd13;
  localparam XOR_state = 5'd14;
  localparam AND_state = 5'd15;
  localparam OR_state = 5'd16;
  localparam A_state = 5'd17;
  localparam B_state = 5'd18;
  localparam SHL_state = 5'd19;
  localparam SHR_state = 5'd20;
  localparam SRA_state = 5'd21;
  
  reg [4:0] M_state_d, M_state_q = START_state;
  reg [5:0] M_alufn_df_d, M_alufn_df_q = 1'h0;
  reg [15:0] M_input_a_df_d, M_input_a_df_q = 1'h0;
  reg [15:0] M_input_b_df_d, M_input_b_df_q = 1'h0;
  reg [15:0] M_display_v_d, M_display_v_q = 1'h0;
  reg [15:0] M_out_d, M_out_q = 1'h0;
  reg M_button_d, M_button_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_button_d = M_button_q;
    M_input_b_df_d = M_input_b_df_q;
    M_display_v_d = M_display_v_q;
    M_input_a_df_d = M_input_a_df_q;
    M_alufn_df_d = M_alufn_df_q;
    M_out_d = M_out_q;
    
    M_alu_alufn = M_alufn_df_q;
    M_alu_a = M_input_a_df_q;
    M_alu_b = M_input_b_df_q;
    M_out_d = M_alu_alu;
    M_display_v_d = 16'h0000;
    
    case (M_state_q)
      START_state: begin
        M_button_d = button_alu;
        M_alufn_df_d = 1'h0;
        M_input_a_df_d = 1'h0;
        M_input_b_df_d = 1'h0;
        M_display_v_d = 16'h18af;
        if (M_button_q) begin
          M_state_d = ADDPOS_state;
        end
      end
      ADDPOS_state: begin
        M_alufn_df_d = 6'h00;
        M_button_d = button_alu;
        M_input_a_df_d = 5'h16;
        M_input_b_df_d = 6'h23;
        if (M_alu_alu == 7'h4d) begin
          M_display_v_d = 16'h11af;
        end
        if (M_button_q) begin
          M_state_d = ADDNEG_state;
        end
      end
      ADDNEG_state: begin
        M_alufn_df_d = 6'h00;
        M_input_a_df_d = $signed(7'h5e);
        M_input_b_df_d = $signed(6'h2b);
        if (M_alu_alu == $signed(7'h49)) begin
          M_display_v_d = 16'h21af;
        end
        if (M_button_q) begin
          M_state_d = OVERFLOW_state;
        end
      end
      OVERFLOW_state: begin
        M_alufn_df_d = 6'h00;
        M_input_a_df_d = 15'h7fff;
        M_input_b_df_d = 1'h1;
        if (M_alu_alu == 16'h8000) begin
          M_display_v_d = 16'h31af;
        end
        if (M_button_q) begin
          M_state_d = SUBPOS_state;
        end
      end
      SUBPOS_state: begin
        M_alufn_df_d = 6'h01;
        M_input_a_df_d = 7'h78;
        M_input_b_df_d = 7'h50;
        if (M_alu_alu == 6'h32) begin
          M_display_v_d = 16'h411f;
        end
        if (M_button_q) begin
          M_state_d = SUBNEG_state;
        end
      end
      SUBNEG_state: begin
        M_alufn_df_d = 6'h01;
        M_input_a_df_d = $signed(7'h60);
        M_input_b_df_d = $signed(6'h29);
        if (M_alu_alu == $signed(5'h17)) begin
          M_display_v_d = 16'h51af;
        end
        if (M_button_q) begin
          M_state_d = UNDERFLOW_state;
        end
      end
      UNDERFLOW_state: begin
        M_alufn_df_d = 6'h01;
        M_input_a_df_d = $signed(17'h18000);
        M_input_b_df_d = $signed(2'h3);
        if (M_alu_alu == $signed(17'h17fff)) begin
          M_display_v_d = 16'h611f;
        end
        if (M_button_q) begin
          M_state_d = MULT_state;
        end
      end
      MULT_state: begin
        M_alufn_df_d = 6'h02;
        M_input_a_df_d = 6'h20;
        M_input_b_df_d = 2'h2;
        if (M_alu_alu == 7'h40) begin
          M_display_v_d = 16'h71af;
        end
        if (M_button_q) begin
          M_state_d = DIV_state;
        end
      end
      DIV_state: begin
        M_alufn_df_d = 6'h03;
        M_input_a_df_d = 6'h20;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 3'h4) begin
          M_display_v_d = 16'h81af;
        end
        if (M_button_q) begin
          M_state_d = CMPLEV_state;
        end
      end
      CMPLEV_state: begin
        M_alufn_df_d = 6'h37;
        M_input_a_df_d = 4'h8;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 1'h1) begin
          M_display_v_d = 16'h91af;
        end
        if (M_button_q) begin
          M_state_d = CMPLEI_state;
        end
      end
      CMPLEI_state: begin
        M_alufn_df_d = 6'h37;
        M_input_a_df_d = $signed(13'h100f);
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 1'h1) begin
          M_display_v_d = 16'h10af;
        end
        if (M_button_q) begin
          M_state_d = CMPLTV_state;
        end
      end
      CMPLTV_state: begin
        M_alufn_df_d = 6'h35;
        M_input_a_df_d = 2'h2;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 1'h0) begin
          M_display_v_d = 16'h111f;
        end
        if (M_button_q) begin
          M_state_d = CMPLTI_state;
        end
      end
      CMPLTI_state: begin
        M_alufn_df_d = 6'h35;
        M_input_a_df_d = $signed(13'h100f);
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 1'h1) begin
          M_display_v_d = 16'h12af;
        end
        if (M_button_q) begin
          M_state_d = CMPEQ_state;
        end
      end
      CMPEQ_state: begin
        M_alufn_df_d = 6'h33;
        M_input_a_df_d = 3'h7;
        M_input_b_df_d = 3'h7;
        if (M_alu_alu == 1'h1) begin
          M_display_v_d = 16'h13af;
        end
        if (M_button_q) begin
          M_state_d = XOR_state;
        end
      end
      XOR_state: begin
        M_alufn_df_d = 6'h16;
        M_input_a_df_d = 3'h6;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 4'he) begin
          M_display_v_d = 16'h14af;
        end
        if (M_button_q) begin
          M_state_d = AND_state;
        end
      end
      AND_state: begin
        M_alufn_df_d = 6'h18;
        M_input_a_df_d = 3'h6;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 1'h0) begin
          M_display_v_d = 16'h15af;
        end
        if (M_button_q) begin
          M_state_d = OR_state;
        end
      end
      OR_state: begin
        M_alufn_df_d = 6'h1e;
        M_input_a_df_d = 3'h6;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 4'he) begin
          M_display_v_d = 16'h16af;
        end
        if (M_button_q) begin
          M_state_d = A_state;
        end
      end
      A_state: begin
        M_alufn_df_d = 6'h1a;
        M_input_a_df_d = 3'h6;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 3'h6) begin
          M_display_v_d = 16'h17af;
        end
        if (M_button_q) begin
          M_state_d = B_state;
        end
      end
      B_state: begin
        M_alufn_df_d = 6'h1a;
        M_input_a_df_d = 3'h6;
        M_input_b_df_d = 4'h8;
        if (M_alu_alu == 4'h8) begin
          M_display_v_d = 16'h18af;
        end
        if (M_button_q) begin
          M_state_d = SHL_state;
        end
      end
      SHL_state: begin
        M_alufn_df_d = 6'h20;
        M_input_a_df_d = 4'hf;
        M_input_b_df_d = 2'h2;
        if (M_alu_alu == 6'h3c) begin
          M_display_v_d = 16'h19af;
        end
        if (M_button_q) begin
          M_state_d = SHR_state;
        end
      end
      SHR_state: begin
        M_alufn_df_d = 6'h21;
        M_input_a_df_d = 7'h40;
        M_input_b_df_d = 2'h3;
        if (M_alu_alu == 4'h8) begin
          M_display_v_d = 16'h20af;
        end
        if (M_button_q) begin
          M_state_d = SRA_state;
        end
      end
      SRA_state: begin
        M_alufn_df_d = 6'h23;
        M_input_a_df_d = 8'hc0;
        M_input_b_df_d = 3'h4;
        if (M_alu_alu == 8'hfc) begin
          M_display_v_d = 16'h21af;
        end
        if (M_button_q) begin
          M_state_d = START_state;
        end
      end
    endcase
    display = M_display_v_q;
  end
  
  always @(posedge clk) begin
    M_alufn_df_q <= M_alufn_df_d;
    M_input_a_df_q <= M_input_a_df_d;
    M_input_b_df_q <= M_input_b_df_d;
    M_display_v_q <= M_display_v_d;
    M_out_q <= M_out_d;
    M_button_q <= M_button_d;
    
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
